CC=gcc
CFLAGS= -std=c17 -pedantic -Wall
BUILD_DIR=build
SRC_DIR=source
INC_DIR=include
INCLUDE=-I$(INC_DIR)
NOM_ZIP=TP1_AMIRHOSSEIN_POUYANFAR.zip

SOURCES=$(wildcard $(SRC_DIR)/*.c)
HEADERS=$(wildcard $(INC_DIR)/*.h)





mytee: $(CC) $(CFLAGS) -o mytee   	